"""
backend/seed_agent_all_a1_topics.py — Runs ContentPedagogyAgent across all 20 standard A1 topics.
"""

import os
import sys
import asyncio
import logging

if sys.stdout.encoding != 'utf-8':
    sys.stdout.reconfigure(encoding='utf-8')

if not os.getenv("OPENAI_API_KEY"):
    pass

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")

from agents.content_agent import ContentPedagogyAgent
from services.openai_service import A1_GRAMMAR_TOPICS
from supabase import create_client

url = os.getenv('SUPABASE_URL', '')
key = os.getenv('SUPABASE_SERVICE_ROLE_KEY', '')

sb = create_client(url, key)

async def main():
    print("=" * 75)
    print("🧹 Cleaning obsolete topics and aligning Agent with standard 20 A1 topics...")
    print("=" * 75)

    # 1. Clean existing tables
    sb.from_('exercises').delete().neq('id', '00000000-0000-0000-0000-000000000000').execute()
    sb.from_('grammar_content').delete().neq('id', '00000000-0000-0000-0000-000000000000').execute()
    sb.from_('grammar_topics').delete().neq('id', '00000000-0000-0000-0000-000000000000').execute()

    agent = ContentPedagogyAgent()

    print(f"🚀 ContentPedagogyAgent seeding lessons and exercises for all {len(A1_GRAMMAR_TOPICS)} A1 topics...")

    for idx, t in enumerate(A1_GRAMMAR_TOPICS, 1):
        topic_code = t["topic_code"]
        order_index = t["order_index"]
        print(f"\n[{idx}/{len(A1_GRAMMAR_TOPICS)}] 🤖 Agent processing topic: '{topic_code}'...")

        try:
            res = await agent.run_full_pipeline_for_topic(
                target_language_code="en",
                native_language_code="fa",
                level_code="A1",
                topic_code=topic_code,
                order_index=order_index,
            )
            print(f"  ✅ Agent Completed '{topic_code}': Saved lesson with 8 main examples & exercises in Supabase.")
        except Exception as e:
            print(f"  ❌ Agent error on '{topic_code}': {e}")

        await asyncio.sleep(0.3)

    print("\n" + "=" * 75)
    print("🎉 ALL 20 A1 TOPICS AND EXERCISES SUCCESSFULLY GENERATED BY AGENT!")
    print("=" * 75)

if __name__ == "__main__":
    asyncio.run(main())
