// lib/core/utils/localization_helper.dart

import 'dart:ui' as ui;
import 'package:shared_preferences/shared_preferences.dart';
import '../constants/app_constants.dart';

class LocalizationHelper {
  LocalizationHelper._();

  static const Map<String, String> nativeLanguageNames = {
    'en': 'English',
    'da': 'Dansk',
    'fa': 'فارسی (Persian)',
    'de': 'Deutsch',
    'fr': 'Français',
    'es': 'Español',
    'ar': 'العربية (Arabic)',
  };

  static const Map<String, String> nativeLanguageFlags = {
    'en': '🇬🇧',
    'da': '🇩🇰',
    'fa': '🇮🇷',
    'de': '🇩🇪',
    'fr': '🇫🇷',
    'es': '🇪🇸',
    'ar': '🇸🇦',
  };

  /// Detect device system language or fallback to English
  static String getDeviceLanguageCode() {
    final systemLocale = ui.PlatformDispatcher.instance.locale.languageCode.toLowerCase();
    if (nativeLanguageNames.containsKey(systemLocale)) {
      return systemLocale;
    }
    return 'en';
  }

  /// Get current user's preferred explanation language
  static Future<String> getSelectedExplanationLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    final saved = prefs.getString(AppConstants.keyNativeLanguage);
    if (saved != null && saved.isNotEmpty) {
      return saved;
    }
    // Default to device locale if available, else 'en'
    final deviceLang = getDeviceLanguageCode();
    await prefs.setString(AppConstants.keyNativeLanguage, deviceLang);
    return deviceLang;
  }

  /// Set user's preferred explanation language
  static Future<void> setSelectedExplanationLanguage(String langCode) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(AppConstants.keyNativeLanguage, langCode);
  }

  /// Basic UI translations for standard navigation strings
  static String tr(String key, {String lang = 'en'}) {
    final translations = _strings[lang] ?? _strings['en']!;
    return translations[key] ?? _strings['en']?[key] ?? key;
  }

  static String _cachedLang = 'en';

  static Future<void> initDeviceLanguage() async {
    _cachedLang = await getSelectedExplanationLanguage();
  }

  static String get currentLang => _cachedLang;

  static const Map<String, Map<String, String>> _strings = {
    'en': {
      'your_choice': 'Choose Your Focus ✨',
      'choose_section': 'What would you like to practice? Grammar or Vocabulary?',
      'grammar_title': 'Grammar',
      'grammar_desc': 'Structured grammar lessons from A1 to C2 with rules, contrasts, and real examples.',
      'vocab_title': 'Vocabulary',
      'vocab_desc': 'Essential vocabulary, words by CEFR level, definitions, and flashcards.',
      'grammar_badge': 'A1 - C2 Lessons',
      'vocab_badge': 'Words & Cards',
      'enter_section': 'Enter Section',
      'explanation_language': 'Explanation Language',
      'change_language': 'Change',
      'grammar_explanation': 'Grammar Explanation',
      'grammar_comparison': 'Grammar Difference with Native Language',
      'active_level': 'Active Level',
      'target_language': 'Target Language',
      'topics_to_review': 'Topics that need review and practice',
      'no_weaknesses': 'Great! No weak points recorded yet.',
      'practice_again': 'Practice Again',
      'try_again': 'Try Again',
      'learner_progress': 'Learner Progress',
      'error_loading': 'Error loading progress data',
      'user': 'User',
      'native_language_label': 'Native language',
      'english_lang': 'English 🇬🇧',
      'level_1_label': 'Stage 1',
      'level_1_title': 'Beginner (A1)',
      'level_1_desc': 'Grammar in your native language, basic sentences and introductions.',
      'level_2_label': 'Stage 2',
      'level_2_title': 'Elementary (A2)',
      'level_2_desc': 'Everyday phrases, grammar differences and common conversations.',
      'level_3_label': 'Stage 3',
      'level_3_title': 'Intermediate (B1)',
      'level_3_desc': 'Expressing opinions, travel and communicating in various situations.',
      'level_4_label': 'Stage 4',
      'level_4_title': 'Upper Intermediate (B2)',
      'level_4_desc': 'Understanding complex texts and fluent conversation.',
      'level_5_label': 'Stage 5',
      'level_5_title': 'Advanced (C1)',
      'level_5_desc': 'Mastery and fluent, effortless expression.',
      'level_6_label': 'Stage 6',
      'level_6_title': 'Proficiency (C2)',
      'level_6_desc': 'Complete understanding and precise expression in complex situations.',
    },
    'da': {
      'your_choice': 'Vælg dit fokus ✨',
      'choose_section': 'Hvad vil du gerne øve? Grammatik eller ordforråd?',
      'grammar_title': 'Grammatik (Grammar)',
      'grammar_desc': 'Strukturerede grammatiklektioner fra A1 til C2 med forklaringer og eksempler.',
      'vocab_title': 'Ordforråd (Vocabulary)',
      'vocab_desc': 'Vigtige ord efter CEFR-niveau, udtale, definitioner og flashcards.',
      'grammar_badge': 'A1 - C2 Lektioner',
      'vocab_badge': 'Ord & Kort',
      'enter_section': 'Gå til sektion',
      'explanation_language': 'Forklaringssprog',
      'change_language': 'Skift',
      'grammar_explanation': 'Grammatikforklaring',
      'grammar_comparison': 'Grammatikforskel med modersmål',
      'active_level': 'Aktivt niveau',
      'target_language': 'Målsprog',
      'topics_to_review': 'Emner, der kræver gennemgang og øvelse',
      'no_weaknesses': 'Fantastisk! Ingen svage punkter registreret endnu.',
      'practice_again': 'Øv igen',
      'try_again': 'Prøv igen',
      'learner_progress': 'Elevens fremskridt',
      'error_loading': 'Fejl ved indlæsning af fremskridtsdata',
      'user': 'Bruger',
      'native_language_label': 'Modersmål',
      'english_lang': 'Engelsk 🇬🇧',
      'level_1_label': 'Trin 1',
      'level_1_title': 'Begynder (A1)',
      'level_1_desc': 'Grammatik på dit modersmål, grundlæggende sætninger og introduktioner.',
      'level_2_label': 'Trin 2',
      'level_2_title': 'Elementær (A2)',
      'level_2_desc': 'Hverdagsudtryk, grammatikforskelle og almindelige samtaler.',
      'level_3_label': 'Trin 3',
      'level_3_title': 'Mellemniveau (B1)',
      'level_3_desc': 'Udtrykke meninger, rejser og kommunikere i forskellige situationer.',
      'level_4_label': 'Trin 4',
      'level_4_title': 'Øvet (B2)',
      'level_4_desc': 'Forståelse af komplekse tekster og flydende samtale.',
      'level_5_label': 'Trin 5',
      'level_5_title': 'Avanceret (C1)',
      'level_5_desc': 'Mestring og flydende, ubesværet udtryk.',
      'level_6_label': 'Trin 6',
      'level_6_title': 'Færdighed (C2)',
      'level_6_desc': 'Fuldstændig forståelse og præcist udtryk i komplekse situationer.',
    },
    'fa': {
      'your_choice': 'حق انتخاب شما ✨',
      'choose_section': 'چه بخشی را می‌خواهید شروع کنید؟ گرامر یا لغات؟',
      'grammar_title': 'گرامر (Grammar)',
      'grammar_desc': 'آموزش گرامر از سطح A1 تا C2 همراه با توضیح تفاوت‌ها و مثال‌های کاربردی.',
      'vocab_title': 'لغات (Vocabulary)',
      'vocab_desc': 'آموزش و مرور لغات کاربردی، اصطلاحات و کلمات سطح‌بندی شده.',
      'grammar_badge': 'سطوح A1 تا C2',
      'vocab_badge': 'کلمات و فلش‌کارت',
      'enter_section': 'ورود به این بخش',
      'explanation_language': 'زبان توضیحات درس',
      'change_language': 'تغییر',
      'grammar_explanation': 'توضیحات گرامر',
      'grammar_comparison': 'تفاوت گرامری با زبان مادری',
      'active_level': 'سطح فعال',
      'target_language': 'زبان هدف',
      'topics_to_review': 'موضوعاتی که نیاز به مرور و تمرین دارند',
      'no_weaknesses': 'عالی! هنوز نقطه ضعفی ثبت نشده است.',
      'practice_again': 'تمرین مجدد',
      'try_again': 'تلاش مجدد',
      'learner_progress': 'پیشرفت زبان‌آموز',
      'error_loading': 'خطا در بارگذاری اطلاعات پیشرفت',
      'user': 'کاربر',
      'native_language_label': 'زبان مادری',
      'english_lang': 'انگلیسی 🇬🇧',
      'level_1_label': 'مرحله ۱',
      'level_1_title': 'مبتدی (A1)',
      'level_1_desc': 'گرامر به زبان مادری، جملات پایه و معرفی.',
      'level_2_label': 'مرحله ۲',
      'level_2_title': 'مقدماتی (A2)',
      'level_2_desc': 'عبارات روزمره، تفاوت‌های گرامری و مکالمات رایج.',
      'level_3_label': 'مرحله ۳',
      'level_3_title': 'متوسط (B1)',
      'level_3_desc': 'بیان نظرات، سفر و برقراری ارتباط در موقعیت‌های مختلف.',
      'level_4_label': 'مرحله ۴',
      'level_4_title': 'فرامتوسط (B2)',
      'level_4_desc': 'درک متون پیچیده و مکالمه روان.',
      'level_5_label': 'مرحله ۵',
      'level_5_title': 'پیشرفته (C1)',
      'level_5_desc': 'تسلط و بیان روان و بدون تلاش.',
      'level_6_label': 'مرحله ۶',
      'level_6_title': 'تسلط کامل (C2)',
      'level_6_desc': 'درک کامل و بیان دقیق در موقعیت‌های پیچیده.',
    },
    'de': {
      'your_choice': 'Wähle deinen Schwerpunkt ✨',
      'choose_section': 'Was möchtest du üben? Grammatik oder Wortschatz?',
      'grammar_title': 'Grammatik (Grammar)',
      'grammar_desc': 'Strukturierte Grammatiklektionen von A1 bis C2 mit Beispielen.',
      'vocab_title': 'Wortschatz (Vocabulary)',
      'vocab_desc': 'Wichtige Vokabeln nach CEFR-Niveau und Karteikarten.',
      'grammar_badge': 'A1 - C2 Lektionen',
      'vocab_badge': 'Wörter & Karten',
      'enter_section': 'Bereich betreten',
      'explanation_language': 'Erklärungssprache',
      'change_language': 'Ändern',
      'grammar_explanation': 'Grammatikerklärung',
      'grammar_comparison': 'Grammatikunterschied zur Muttersprache',
      'active_level': 'Aktives Niveau',
      'target_language': 'Zielsprache',
      'topics_to_review': 'Themen, die überprüft und geübt werden müssen',
      'no_weaknesses': 'Großartig! Bisher keine Schwachstellen erfasst.',
      'practice_again': 'Noch einmal üben',
      'try_again': 'Erneut versuchen',
      'learner_progress': 'Lernfortschritt',
      'error_loading': 'Fehler beim Laden der Fortschrittsdaten',
      'user': 'Benutzer',
      'native_language_label': 'Muttersprache',
      'english_lang': 'Englisch 🇬🇧',
      'level_1_label': 'Stufe 1',
      'level_1_title': 'Anfänger (A1)',
      'level_1_desc': 'Grammatik in Ihrer Muttersprache, grundlegende Sätze und Vorstellungen.',
      'level_2_label': 'Stufe 2',
      'level_2_title': 'Elementar (A2)',
      'level_2_desc': 'Alltagsausdrücke, Grammatikunterschiede und allgemeine Gespräche.',
      'level_3_label': 'Stufe 3',
      'level_3_title': 'Mittelstufe (B1)',
      'level_3_desc': 'Meinungen äußern, reisen und sich in verschiedenen Situationen verständigen.',
      'level_4_label': 'Stufe 4',
      'level_4_title': 'Obere Mittelstufe (B2)',
      'level_4_desc': 'Verstehen komplexer Texte und fließende Konversation.',
      'level_5_label': 'Stufe 5',
      'level_5_title': 'Fortgeschritten (C1)',
      'level_5_desc': 'Beherrschung und fließender, müheloser Ausdruck.',
      'level_6_label': 'Stufe 6',
      'level_6_title': 'Kompetent (C2)',
      'level_6_desc': 'Vollständiges Verständnis und präziser Ausdruck in komplexen Situationen.',
    },
    'fr': {
      'your_choice': 'Choisissez votre parcours ✨',
      'choose_section': 'Que voulez-vous pratiquer ? Grammaire ou Vocabulaire ?',
      'grammar_title': 'Grammaire (Grammar)',
      'grammar_desc': 'Leçons de grammaire structurées du A1 au C2 avec règles et exemples.',
      'vocab_title': 'Vocabulaire (Vocabulary)',
      'vocab_desc': 'Vocabulaire essentiel par niveau CECRL et cartes mémoire.',
      'grammar_badge': 'Leçons A1 - C2',
      'vocab_badge': 'Mots & Cartes',
      'enter_section': 'Accéder',
      'explanation_language': 'Langue des explications',
      'change_language': 'Changer',
      'grammar_explanation': 'Explication de la grammaire',
      'grammar_comparison': 'Différence de grammaire avec la langue maternelle',
      'active_level': 'Niveau actif',
      'target_language': 'Langue cible',
      'topics_to_review': 'Sujets nécessitant une révision et de la pratique',
      'no_weaknesses': 'Super ! Aucun point faible enregistré pour le moment.',
      'practice_again': 'Pratiquer à nouveau',
      'try_again': 'Réessayer',
      'learner_progress': 'Progrès de l\'apprenant',
      'error_loading': 'Erreur lors du chargement des données de progression',
      'user': 'Utilisateur',
      'native_language_label': 'Langue maternelle',
      'english_lang': 'Anglais 🇬🇧',
      'level_1_label': 'Étape 1',
      'level_1_title': 'Débutant (A1)',
      'level_1_desc': 'Grammaire dans votre langue maternelle, phrases de base et présentations.',
      'level_2_label': 'Étape 2',
      'level_2_title': 'Élémentaire (A2)',
      'level_2_desc': 'Phrases quotidiennes, différences de grammaire et conversations courantes.',
      'level_3_label': 'Étape 3',
      'level_3_title': 'Intermédiaire (B1)',
      'level_3_desc': 'Exprimer des opinions, voyager et communiquer dans diverses situations.',
      'level_4_label': 'Étape 4',
      'level_4_title': 'Intermédiaire supérieur (B2)',
      'level_4_desc': 'Compréhension de textes complexes et conversation courante.',
      'level_5_label': 'Étape 5',
      'level_5_title': 'Avancé (C1)',
      'level_5_desc': 'Maîtrise et expression fluide et sans effort.',
      'level_6_label': 'Étape 6',
      'level_6_title': 'Compétent (C2)',
      'level_6_desc': 'Compréhension complète et expression précise dans des situations complexes.',
    },
    'es': {
      'your_choice': 'Elige tu enfoque ✨',
      'choose_section': '¿Qué te gustaría practicar? ¿Gramática o Vocabulario?',
      'grammar_title': 'Gramática (Grammar)',
      'grammar_desc': 'Lecciones de gramática estructuradas de A1 a C2 con reglas y ejemplos.',
      'vocab_title': 'Vocabulario (Vocabulary)',
      'vocab_desc': 'Vocabulario esencial por nivel MCER y tarjetas didácticas.',
      'grammar_badge': 'Lecciones A1 - C2',
      'vocab_badge': 'Palabras y Tarjetas',
      'enter_section': 'Entrar a la sección',
      'explanation_language': 'Idioma de explicación',
      'change_language': 'Cambiar',
      'grammar_explanation': 'Explicación de la gramática',
      'grammar_comparison': 'Diferencia gramatical con el idioma nativo',
      'active_level': 'Nivel activo',
      'target_language': 'Idioma de destino',
      'topics_to_review': 'Temas que necesitan revisión y práctica',
      'no_weaknesses': '¡Genial! Aún no se han registrado puntos débiles.',
      'practice_again': 'Practicar de nuevo',
      'try_again': 'Intentar de nuevo',
      'learner_progress': 'Progreso del estudiante',
      'error_loading': 'Error al cargar los datos de progreso',
      'user': 'Usuario',
      'native_language_label': 'Idioma nativo',
      'english_lang': 'Inglés 🇬🇧',
      'level_1_label': 'Etapa 1',
      'level_1_title': 'Principiante (A1)',
      'level_1_desc': 'Gramática en su idioma nativo, oraciones básicas y presentaciones.',
      'level_2_label': 'Etapa 2',
      'level_2_title': 'Elemental (A2)',
      'level_2_desc': 'Frases cotidianas, diferencias gramaticales y conversaciones comunes.',
      'level_3_label': 'Etapa 3',
      'level_3_title': 'Intermedio (B1)',
      'level_3_desc': 'Expresar opiniones, viajar y comunicarse en diversas situaciones.',
      'level_4_label': 'Etapa 4',
      'level_4_title': 'Intermedio alto (B2)',
      'level_4_desc': 'Comprensión de textos complejos y conversación fluida.',
      'level_5_label': 'Etapa 5',
      'level_5_title': 'Avanzado (C1)',
      'level_5_desc': 'Dominio y expresión fluida y sin esfuerzo.',
      'level_6_label': 'Etapa 6',
      'level_6_title': 'Dominio (C2)',
      'level_6_desc': 'Comprensión completa y expresión precisa en situaciones complejas.',
    },
  };
}
